name: Testes API Postman

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g newman newman-reporter-html

    - name: Start API
      run: |
        nohup node API/index.js &
        sleep 5

    - name: Create Postman Environment dynamically
      run: |
        echo '{
          "name": "Localhost",
          "values": [
            { "key": "baseUrl", "value": "http://localhost:3000", "enabled": true }
          ]
        }' > Localhost.postman_environment.json

    - name: Run Postman Collection with CSV data
      run: |
        newman run collections/Treino.postman_collection.json \
          -e Localhost.postman_environment.json \
          -d data/soma.csv \
          -r cli,html
